namespace ReflexHL7.CodeGenerator;

internal abstract record TargetToGenerate(string Name, string NamespaceName)
{
    private static readonly string _assemblyVersion;
    private static readonly string _toolName;

    static TargetToGenerate()
    {
        var assemblyName = typeof(TargetToGenerate).Assembly.GetName();

        _assemblyVersion = assemblyName.Version.ToString();
        _toolName = assemblyName.Name;
    }

    public abstract string GenerateReadMethod();

    protected static void WriteEpilogue(CodeStringBuilder csb)
    {
        csb.Unindent();
        csb.AppendLine("}");
        csb.Unindent();
        csb.AppendLine("}");
    }

    protected CodeStringBuilder WritePrologue()
    {
        var csb = new CodeStringBuilder();

        csb.AppendLine("//------------------------------------------------------------------------------");
        csb.AppendLine("// <auto-generated>");
        csb.AppendLine($"//     This code was generated by the {_toolName} tool.");
        csb.AppendLine($"//     Version: {_assemblyVersion}");
        csb.AppendLine("//");
        csb.AppendLine("//     Changes to this file may cause incorrect behaviour and will be lost");
        csb.AppendLine("//     when the containing project is built.");
        csb.AppendLine("// </auto-generated>");
        csb.AppendLine("//------------------------------------------------------------------------------");
        csb.AppendLine();
        csb.AppendLine($"namespace {NamespaceName};");
        csb.AppendLine();
        csb.AppendLine($"public partial class {Name}");
        csb.AppendLine("{");
        csb.Indent();
        csb.AppendLine("/// <summary>");
        csb.AppendLine("/// Read the HL7 V2 object from the supplied token stream.");
        csb.AppendLine("/// </summary>");
        csb.AppendLine("/// <param name=\"tokeniser\">The tokeniser to read the object from.");
        csb.AppendLine("/// </param>");
        csb.AppendLine("/// <returns>The parsed HL7 V2 object or null if not available.</returns>");
        csb.AppendLine($"public static {Name} Read(ReflexHL7.HL7Tokeniser tokeniser)");
        csb.AppendLine("{");
        csb.Indent();

        return csb;
    }
}